version: "3.9"
  
services:
  api:
   image: learn
   environment:
    - MONGO_URI=mongodb://localhost:27017/
    - MONGO_DATABASE=e-learning
    - REDIS_URI=redis:6379
   networks:
    - api_network
   external_links:
     - mongodb
     - redis
   deploy:
    replicas: 5
  redis:
   image: redis
   networks:
    - api_network
  mongodb:
   image: mongo:4.4.3
   networks:
     - api_network
  nginx:
   image: nginx
   ports:
    - 80:80
   volumes:
   - $PWD/nginx.conf:/etc/nginx/nginx.conf
   depends_on:
   - api
   networks:
   - api_network
networks:
 api_network:
